# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import caplinked
from caplinked.rest import ApiException
from caplinked.apis.files_api import FilesApi


class TestFilesApi(unittest.TestCase):
    """ FilesApi unit test stubs """

    def setUp(self):
        self.api = caplinked.apis.files_api.FilesApi()

    def tearDown(self):
        pass

    def test_delete_files_id(self):
        """
        Test case for delete_files_id

        Delete file
        """
        pass

    def test_get_files_id(self):
        """
        Test case for get_files_id

        Get file information
        """
        pass

    def test_post_files_id_copy(self):
        """
        Test case for post_files_id_copy

        Copy file
        """
        pass

    def test_post_files_id_move(self):
        """
        Test case for post_files_id_move

        Move file
        """
        pass

    def test_put_files_id(self):
        """
        Test case for put_files_id

        Update file information
        """
        pass

    def test_put_files_upload(self):
        """
        Test case for put_files_upload

        Upload file
        """
        pass


if __name__ == '__main__':
    unittest.main()
