# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import caplinked
from caplinked.rest import ApiException
from caplinked.apis.folders_api import FoldersApi


class TestFoldersApi(unittest.TestCase):
    """ FoldersApi unit test stubs """

    def setUp(self):
        self.api = caplinked.apis.folders_api.FoldersApi()

    def tearDown(self):
        pass

    def test_delete_folders_id(self):
        """
        Test case for delete_folders_id

        Delete folder
        """
        pass

    def test_get_folders_id(self):
        """
        Test case for get_folders_id

        Get folder information
        """
        pass

    def test_post_folders(self):
        """
        Test case for post_folders

        Create new folder
        """
        pass

    def test_post_folders_id_copy(self):
        """
        Test case for post_folders_id_copy

        Copy folder
        """
        pass

    def test_post_folders_id_move(self):
        """
        Test case for post_folders_id_move

        Move folder
        """
        pass

    def test_put_folders_id(self):
        """
        Test case for put_folders_id

        Update folder information
        """
        pass


if __name__ == '__main__':
    unittest.main()
