# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import caplinked
from caplinked.rest import ApiException
from caplinked.apis.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """ UsersApi unit test stubs """

    def setUp(self):
        self.api = caplinked.apis.users_api.UsersApi()

    def tearDown(self):
        pass

    def test_delete_users(self):
        """
        Test case for delete_users

        Delete user
        """
        pass

    def test_get_users_me(self):
        """
        Test case for get_users_me

        Get user information
        """
        pass

    def test_post_users(self):
        """
        Test case for post_users

        Create user
        """
        pass

    def test_put_users_me(self):
        """
        Test case for put_users_me

        Update a user
        """
        pass


if __name__ == '__main__':
    unittest.main()
