# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import caplinked
from caplinked.rest import ApiException
from caplinked.models.file_copy_move import FileCopyMove


class TestFileCopyMove(unittest.TestCase):
    """ FileCopyMove unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileCopyMove(self):
        """
        Test FileCopyMove
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = caplinked.models.file_copy_move.FileCopyMove()
        pass


if __name__ == '__main__':
    unittest.main()
