# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import caplinked
from caplinked.rest import ApiException
from caplinked.apis.watermark_api import WatermarkApi


class TestWatermarkApi(unittest.TestCase):
    """ WatermarkApi unit test stubs """

    def setUp(self):
        self.api = caplinked.apis.watermark_api.WatermarkApi()

    def tearDown(self):
        pass

    def test_delete_watermark_id(self):
        """
        Test case for delete_watermark_id

        Delete custom watermark
        """
        pass

    def test_get_watermark_id(self):
        """
        Test case for get_watermark_id

        Get custom watermark setting
        """
        pass

    def test_post_watermark(self):
        """
        Test case for post_watermark

        Add custom watermark
        """
        pass

    def test_put_watermark_id(self):
        """
        Test case for put_watermark_id

        Update custom watermark
        """
        pass


if __name__ == '__main__':
    unittest.main()
