# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import caplinked
from caplinked.rest import ApiException
from caplinked.apis.permissions_api import PermissionsApi


class TestPermissionsApi(unittest.TestCase):
    """ PermissionsApi unit test stubs """

    def setUp(self):
        self.api = caplinked.apis.permissions_api.PermissionsApi()

    def tearDown(self):
        pass

    def test_get_permissions_folders_id(self):
        """
        Test case for get_permissions_folders_id

        List subfolder permissions
        """
        pass

    def test_put_permissions_folders_id(self):
        """
        Test case for put_permissions_folders_id

        Update folder permissions
        """
        pass


if __name__ == '__main__':
    unittest.main()
