# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import caplinked
from caplinked.rest import ApiException
from caplinked.apis.activities_api import ActivitiesApi


class TestActivitiesApi(unittest.TestCase):
    """ ActivitiesApi unit test stubs """

    def setUp(self):
        self.api = caplinked.apis.activities_api.ActivitiesApi()

    def tearDown(self):
        pass

    def test_get_activities_workspace_workspace_id(self):
        """
        Test case for get_activities_workspace_workspace_id

        Get workspace activities
        """
        pass


if __name__ == '__main__':
    unittest.main()
