# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import caplinked
from caplinked.rest import ApiException
from caplinked.apis.organization_api import OrganizationApi


class TestOrganizationApi(unittest.TestCase):
    """ OrganizationApi unit test stubs """

    def setUp(self):
        self.api = caplinked.apis.organization_api.OrganizationApi()

    def tearDown(self):
        pass

    def test_delete_organization_memberships(self):
        """
        Test case for delete_organization_memberships

        Remove organization admin membership
        """
        pass

    def test_get_organization(self):
        """
        Test case for get_organization

        Get organization information
        """
        pass

    def test_get_organization_memberships(self):
        """
        Test case for get_organization_memberships

        Show all organization members
        """
        pass

    def test_post_organization_memberships(self):
        """
        Test case for post_organization_memberships

        Add organization admin membership
        """
        pass

    def test_put_organization(self):
        """
        Test case for put_organization

        Update organization information
        """
        pass

    def test_put_organization_support_information(self):
        """
        Test case for put_organization_support_information

        Update support information of organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
