# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import caplinked
from caplinked.rest import ApiException
from caplinked.apis.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """ GroupsApi unit test stubs """

    def setUp(self):
        self.api = caplinked.apis.groups_api.GroupsApi()

    def tearDown(self):
        pass

    def test_delete_groups_id(self):
        """
        Test case for delete_groups_id

        Delete group
        """
        pass

    def test_delete_groups_id_memberships(self):
        """
        Test case for delete_groups_id_memberships

        Remove a user from a group
        """
        pass

    def test_get_groups(self):
        """
        Test case for get_groups

        List all groups in workspace
        """
        pass

    def test_get_groups_id(self):
        """
        Test case for get_groups_id

        Get group information
        """
        pass

    def test_get_groups_id_memberships(self):
        """
        Test case for get_groups_id_memberships

        List all memberships for a group
        """
        pass

    def test_post_groups(self):
        """
        Test case for post_groups

        Create group
        """
        pass

    def test_post_groups_id_memberships(self):
        """
        Test case for post_groups_id_memberships

        Add user to group (adds to parent workspace if they are not already a member)
        """
        pass

    def test_put_groups_id(self):
        """
        Test case for put_groups_id

        Update group
        """
        pass

    def test_put_groups_id_disable_drm_expiration(self):
        """
        Test case for put_groups_id_disable_drm_expiration

        Disable DRM expiration for group
        """
        pass

    def test_put_groups_id_disable_expire_access(self):
        """
        Test case for put_groups_id_disable_expire_access

        Disable access expiration for a group
        """
        pass

    def test_put_groups_id_drm(self):
        """
        Test case for put_groups_id_drm

        Update DRM for group
        """
        pass

    def test_put_groups_id_enable_expire_access(self):
        """
        Test case for put_groups_id_enable_expire_access

        Enable access expiration for a group
        """
        pass

    def test_put_groups_id_watermarking(self):
        """
        Test case for put_groups_id_watermarking

        Watermarking for group
        """
        pass


if __name__ == '__main__':
    unittest.main()
