# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import caplinked
from caplinked.rest import ApiException
from caplinked.apis.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """ WorkspacesApi unit test stubs """

    def setUp(self):
        self.api = caplinked.apis.workspaces_api.WorkspacesApi()

    def tearDown(self):
        pass

    def test_get_workspaces(self):
        """
        Test case for get_workspaces

        List all workspaces for a team
        """
        pass

    def test_get_workspaces_id(self):
        """
        Test case for get_workspaces_id

        Get workspace information
        """
        pass

    def test_post_workspaces(self):
        """
        Test case for post_workspaces

        Create workspace
        """
        pass

    def test_put_workspaces_id(self):
        """
        Test case for put_workspaces_id

        Update workspace
        """
        pass


if __name__ == '__main__':
    unittest.main()
