# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FileInfoCompact(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'title': 'str',
        'file_name': 'str',
        'file_size': 'str',
        'file_content_type': 'str',
        'index': 'int',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'file_name': 'file_name',
        'file_size': 'file_size',
        'file_content_type': 'file_content_type',
        'index': 'index',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, id=None, title=None, file_name=None, file_size=None, file_content_type=None, index=None, created_at=None, updated_at=None):
        """
        FileInfoCompact - a model defined in Swagger
        """

        self._id = None
        self._title = None
        self._file_name = None
        self._file_size = None
        self._file_content_type = None
        self._index = None
        self._created_at = None
        self._updated_at = None

        if id is not None:
          self.id = id
        if title is not None:
          self.title = title
        if file_name is not None:
          self.file_name = file_name
        if file_size is not None:
          self.file_size = file_size
        if file_content_type is not None:
          self.file_content_type = file_content_type
        if index is not None:
          self.index = index
        if created_at is not None:
          self.created_at = created_at
        if updated_at is not None:
          self.updated_at = updated_at

    @property
    def id(self):
        """
        Gets the id of this FileInfoCompact.

        :return: The id of this FileInfoCompact.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this FileInfoCompact.

        :param id: The id of this FileInfoCompact.
        :type: int
        """

        self._id = id

    @property
    def title(self):
        """
        Gets the title of this FileInfoCompact.

        :return: The title of this FileInfoCompact.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this FileInfoCompact.

        :param title: The title of this FileInfoCompact.
        :type: str
        """

        self._title = title

    @property
    def file_name(self):
        """
        Gets the file_name of this FileInfoCompact.

        :return: The file_name of this FileInfoCompact.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """
        Sets the file_name of this FileInfoCompact.

        :param file_name: The file_name of this FileInfoCompact.
        :type: str
        """

        self._file_name = file_name

    @property
    def file_size(self):
        """
        Gets the file_size of this FileInfoCompact.

        :return: The file_size of this FileInfoCompact.
        :rtype: str
        """
        return self._file_size

    @file_size.setter
    def file_size(self, file_size):
        """
        Sets the file_size of this FileInfoCompact.

        :param file_size: The file_size of this FileInfoCompact.
        :type: str
        """

        self._file_size = file_size

    @property
    def file_content_type(self):
        """
        Gets the file_content_type of this FileInfoCompact.

        :return: The file_content_type of this FileInfoCompact.
        :rtype: str
        """
        return self._file_content_type

    @file_content_type.setter
    def file_content_type(self, file_content_type):
        """
        Sets the file_content_type of this FileInfoCompact.

        :param file_content_type: The file_content_type of this FileInfoCompact.
        :type: str
        """

        self._file_content_type = file_content_type

    @property
    def index(self):
        """
        Gets the index of this FileInfoCompact.

        :return: The index of this FileInfoCompact.
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """
        Sets the index of this FileInfoCompact.

        :param index: The index of this FileInfoCompact.
        :type: int
        """

        self._index = index

    @property
    def created_at(self):
        """
        Gets the created_at of this FileInfoCompact.

        :return: The created_at of this FileInfoCompact.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this FileInfoCompact.

        :param created_at: The created_at of this FileInfoCompact.
        :type: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """
        Gets the updated_at of this FileInfoCompact.

        :return: The updated_at of this FileInfoCompact.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """
        Sets the updated_at of this FileInfoCompact.

        :param updated_at: The updated_at of this FileInfoCompact.
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FileInfoCompact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
