# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FolderCopyMove(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'success': 'int'
    }

    attribute_map = {
        'message': 'message',
        'success': 'success'
    }

    def __init__(self, message=None, success=None):
        """
        FolderCopyMove - a model defined in Swagger
        """

        self._message = None
        self._success = None

        if message is not None:
          self.message = message
        if success is not None:
          self.success = success

    @property
    def message(self):
        """
        Gets the message of this FolderCopyMove.

        :return: The message of this FolderCopyMove.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this FolderCopyMove.

        :param message: The message of this FolderCopyMove.
        :type: str
        """

        self._message = message

    @property
    def success(self):
        """
        Gets the success of this FolderCopyMove.

        :return: The success of this FolderCopyMove.
        :rtype: int
        """
        return self._success

    @success.setter
    def success(self, success):
        """
        Sets the success of this FolderCopyMove.

        :param success: The success of this FolderCopyMove.
        :type: int
        """

        self._success = success

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FolderCopyMove):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
