# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Meta(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'user_id': 'int',
        'file_ids': 'int',
        'folder_ids': 'int',
        'status': 'str',
        'created_at': 'str'
    }

    attribute_map = {
        'id': 'id',
        'user_id': 'user_id',
        'file_ids': 'file_ids',
        'folder_ids': 'folder_ids',
        'status': 'status',
        'created_at': 'created_at'
    }

    def __init__(self, id=None, user_id=None, file_ids=None, folder_ids=None, status=None, created_at=None):
        """
        Meta - a model defined in Swagger
        """

        self._id = None
        self._user_id = None
        self._file_ids = None
        self._folder_ids = None
        self._status = None
        self._created_at = None

        if id is not None:
          self.id = id
        if user_id is not None:
          self.user_id = user_id
        if file_ids is not None:
          self.file_ids = file_ids
        if folder_ids is not None:
          self.folder_ids = folder_ids
        if status is not None:
          self.status = status
        if created_at is not None:
          self.created_at = created_at

    @property
    def id(self):
        """
        Gets the id of this Meta.

        :return: The id of this Meta.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Meta.

        :param id: The id of this Meta.
        :type: int
        """

        self._id = id

    @property
    def user_id(self):
        """
        Gets the user_id of this Meta.

        :return: The user_id of this Meta.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """
        Sets the user_id of this Meta.

        :param user_id: The user_id of this Meta.
        :type: int
        """

        self._user_id = user_id

    @property
    def file_ids(self):
        """
        Gets the file_ids of this Meta.

        :return: The file_ids of this Meta.
        :rtype: int
        """
        return self._file_ids

    @file_ids.setter
    def file_ids(self, file_ids):
        """
        Sets the file_ids of this Meta.

        :param file_ids: The file_ids of this Meta.
        :type: int
        """

        self._file_ids = file_ids

    @property
    def folder_ids(self):
        """
        Gets the folder_ids of this Meta.

        :return: The folder_ids of this Meta.
        :rtype: int
        """
        return self._folder_ids

    @folder_ids.setter
    def folder_ids(self, folder_ids):
        """
        Sets the folder_ids of this Meta.

        :param folder_ids: The folder_ids of this Meta.
        :type: int
        """

        self._folder_ids = folder_ids

    @property
    def status(self):
        """
        Gets the status of this Meta.

        :return: The status of this Meta.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this Meta.

        :param status: The status of this Meta.
        :type: str
        """

        self._status = status

    @property
    def created_at(self):
        """
        Gets the created_at of this Meta.

        :return: The created_at of this Meta.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this Meta.

        :param created_at: The created_at of this Meta.
        :type: str
        """

        self._created_at = created_at

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Meta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
