# coding: utf-8

"""
    CapLinked API v1.0

    Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.

    OpenAPI spec version: 2017-05-23
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SupportInformation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'support_number': 'str',
        'support_email': 'str',
        'support_website': 'str',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'support_number': 'support_number',
        'support_email': 'support_email',
        'support_website': 'support_website',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, support_number=None, support_email=None, support_website=None, created_at=None, updated_at=None):
        """
        SupportInformation - a model defined in Swagger
        """

        self._support_number = None
        self._support_email = None
        self._support_website = None
        self._created_at = None
        self._updated_at = None

        if support_number is not None:
          self.support_number = support_number
        if support_email is not None:
          self.support_email = support_email
        if support_website is not None:
          self.support_website = support_website
        if created_at is not None:
          self.created_at = created_at
        if updated_at is not None:
          self.updated_at = updated_at

    @property
    def support_number(self):
        """
        Gets the support_number of this SupportInformation.

        :return: The support_number of this SupportInformation.
        :rtype: str
        """
        return self._support_number

    @support_number.setter
    def support_number(self, support_number):
        """
        Sets the support_number of this SupportInformation.

        :param support_number: The support_number of this SupportInformation.
        :type: str
        """

        self._support_number = support_number

    @property
    def support_email(self):
        """
        Gets the support_email of this SupportInformation.

        :return: The support_email of this SupportInformation.
        :rtype: str
        """
        return self._support_email

    @support_email.setter
    def support_email(self, support_email):
        """
        Sets the support_email of this SupportInformation.

        :param support_email: The support_email of this SupportInformation.
        :type: str
        """

        self._support_email = support_email

    @property
    def support_website(self):
        """
        Gets the support_website of this SupportInformation.

        :return: The support_website of this SupportInformation.
        :rtype: str
        """
        return self._support_website

    @support_website.setter
    def support_website(self, support_website):
        """
        Sets the support_website of this SupportInformation.

        :param support_website: The support_website of this SupportInformation.
        :type: str
        """

        self._support_website = support_website

    @property
    def created_at(self):
        """
        Gets the created_at of this SupportInformation.

        :return: The created_at of this SupportInformation.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this SupportInformation.

        :param created_at: The created_at of this SupportInformation.
        :type: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """
        Gets the updated_at of this SupportInformation.

        :return: The updated_at of this SupportInformation.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """
        Sets the updated_at of this SupportInformation.

        :param updated_at: The updated_at of this SupportInformation.
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SupportInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
